changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
      - release
  categories:
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Refactors
      labels:
        - refactor
    - title: Tests
      labels:
        - test
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
    - title: Other
      labels:
        - "*"
